### ISSUE TITLE
[feat] cross platform, generic komokana

### ISSUE THREAD

**Issue by Psych3r** [LGUG2Z/komokana#64]
I really like the idea of switching kanata's active layer based on the currently focused application.
Would you be open to making komokana generic in the sense that it can support OS focus change events and not only rely on komorebi?
If so, I'd like to work on this feature.
My Idea is to have an interface for receiving events with multiple "providers" depending on the OS and/or user configuration.
With komerebi being a specific implementation of a provider.
So for example, I am able to listen to focus change events on macOS.
We can have komokana listen to those events on macOS instead of komorebi.
Would like to hear your thoughts on this.

**Comment by LGUG2Z** [comment]
Sounds like a great idea! Would be very happy to integrate a PR that incorporates this provider approach since I'd no doubt use it myself 🙏
